CREATE TABLE working_cs_{instance}
WITH (external_location = '{bucket-name}/working/cs/{path-name}/',
      format = 'PARQUET',
      parquet_compression = 'SNAPPY')
AS
SELECT
  "voyageid"
, "airline_iata"
, "airline_icao"
, "flightnumber"
, "codeshare"
, "operating_flightnumber"
, "flight_date"
, "std"
, "off_block"
, "out"
, "down"
, "on_block"
, "sta"
, "eta"
, "ata"
, "origin_iata"
, "origin_icao"
, "destination_iata"
, "destination_icao"
, "airport_iata"
, "airport_icao"
, "last_next_iata"
, "last_next_icao"
, "orig_dest_iata"
, "orig_dest_icao"
, "aircraft_iata"
, "aircraft_icao"
, "seats"
, "pax"
, "flight_type"
, "pax_flight"
, "origin_status"
, "destination_status"
, "etd"
, "atd"
, "std_datetime_utc"
, "std_datetime_local"
, "std_date_utc"
, "atd_datetime_utc"
, "atd_datetime_local"
, "sta_datetime_utc"
, "sta_datetime_local"
, "sta_date_utc"
, "carrier_md_code"
, "carrier_name"
, "carrier_lcam_name"
, "carrier_cam_name"
, "departure_port_name"
, "departure_port_md_code"
, "departure_port_city"
, "departure_port_lat"
, "departure_port_lon"
, "departure_port_country_md_code"
, "departure_port_country_name"
, "departure_port_continent_name"
, "inbound_risk_tier_name"
, "inbound_risk_category_name"
, "inbound_risk_priority"
, "arrival_port_md_code"
, "arrival_port_name"
, "arrival_port_city"
, "arrival_port_lat"
, "arrival_port_lon"
, "arrival_port_country_md_code"
, "arrival_port_country_name"
, "arrival_port_continent_name"
, "outbound_risk_tier_name"
, "outbound_risk_category_name"
, "outbound_risk_priority"
, "inbound_outbound"
, "voyage_number"
, "voyage_number_trailing"
, "cta_flag"
, "oag_type"
, "acl_type"
, "oag_lastupdated"
, "acl_lastupdated"
, "oag_filename"
, "acl_filename"
, "insert_timestamp"
, "update_timestamp"
, "cs_lastupdated"
, "path_name"
, "carrier_type"
FROM
  (
   SELECT
     "voyageid"
   , "airline_iata"
   , "airline_icao"
   , "flightnumber"
   , "codeshare"
   , "operating_flightnumber"
   , "flight_date"
   , "std"
   , "off_block"
   , "out"
   , "down"
   , "on_block"
   , "sta"
   , "eta"
   , "ata"
   , "origin_iata"
   , "origin_icao"
   , "destination_iata"
   , "destination_icao"
   , "airport_iata"
   , "airport_icao"
   , "last_next_iata"
   , "last_next_icao"
   , "orig_dest_iata"
   , "orig_dest_icao"
   , "aircraft_iata"
   , "aircraft_icao"
   , "seats"
   , "pax"
   , "flight_type"
   , "pax_flight"
   , "origin_status"
   , "destination_status"
   , "etd"
   , "atd"
   , "std_datetime_utc"
   , "std_datetime_local"
   , "std_date_utc"
   , "atd_datetime_utc"
   , "atd_datetime_local"
   , "sta_datetime_utc"
   , "sta_datetime_local"
   , "sta_date_utc"
   , "carrier_md_code"
   , "carrier_name"
   , "carrier_lcam_name"
   , "carrier_cam_name"
   , "departure_port_name"
   , "departure_port_md_code"
   , "departure_port_city"
   , "departure_port_lat"
   , "departure_port_lon"
   , "departure_port_country_md_code"
   , "departure_port_country_name"
   , "departure_port_continent_name"
   , "inbound_risk_tier_name"
   , "inbound_risk_category_name"
   , "inbound_risk_priority"
   , "arrival_port_md_code"
   , "arrival_port_name"
   , "arrival_port_city"
   , "arrival_port_lat"
   , "arrival_port_lon"
   , "arrival_port_country_md_code"
   , "arrival_port_country_name"
   , "arrival_port_continent_name"
   , "outbound_risk_tier_name"
   , "outbound_risk_category_name"
   , "outbound_risk_priority"
   , "inbound_outbound"
   , "voyage_number"
   , "voyage_number_trailing"
   , "cta_flag"
   , "oag_type"
   , "acl_type"
   , "oag_lastupdated"
   , "acl_lastupdated"
   , "oag_filename"
   , "acl_filename"
   , "insert_timestamp"
   , "update_timestamp"
   , "acl_oag_lastupdated"
   , "cs_lastupdated"
   , "path_name"
   , "carrier_type"
   , "row_number"() OVER (PARTITION BY "voyageid" ORDER BY (CASE WHEN ("acl_type" = '0') THEN 1 WHEN ("oag_type" = 'U') THEN 2 ELSE 3 END) ASC, "acl_oag_lastupdated" DESC) "rnum"
    FROM
     (
      SELECT *
      FROM
        consolidated_schedule_{namespace}.internal_storage_table_history
WHERE (path_name >= '{path-name-cs-min}' AND path_name <= '{path-name-cs-max}')
      OR  (path_name >= 'bulk/{path-name-cs-min}' AND path_name <= 'bulk/{path-name-cs-max}')
      OR  (path_name >= 'collected/{path-name-cs-min}' AND path_name <= 'collected/{path-name-cs-max}')
UNION ALL
      SELECT *
      FROM
        consolidated_schedule_{namespace}.internal_storage_table_consolidated
WHERE (path_name >= '{path-name-cs-min}' AND path_name <= '{path-name-cs-max}')
      OR  (path_name >= 'bulk/{path-name-cs-min}' AND path_name <= 'bulk/{path-name-cs-max}')
      OR  (path_name >= 'collected/{path-name-cs-min}' AND path_name <= 'collected/{path-name-cs-max}')
UNION ALL
      SELECT *
      FROM
        consolidated_schedule_{namespace}.internal_storage_table
WHERE (path_name >= '{path-name-cs-min}' AND path_name <= '{path-name-cs-max}')
      OR  (path_name >= 'bulk/{path-name-cs-min}' AND path_name <= 'bulk/{path-name-cs-max}')
      OR  (path_name >= 'input/{rnm-path-name-cs-min}' AND path_name <= 'input/{rnm-path-name-cs-max}')
      OR  (path_name >= 'collected/{path-name-cs-min}' AND path_name <= 'collected/{path-name-cs-max}')
   )  sub
)  sub2
WHERE ("rnum" = 1)
