apiVersion: v1
kind: Pod
metadata:
  name: my-dep2-nginx
  labels:
    rel: stable
    app: nginx
spec:
  containers:
    - name: my-dep2-nginx
      image: nginx:alpine
      ports:
      - containerPort: 80


# kubectl create -f nginix.pod2.yml --save-config
