# app.py
# https://medium.com/bitcraft/docker-composing-a-python-3-flask-app-line-by-line-93b721105777

from flask import Flask
from flask import render_template

app = Flask(__name__)

'''
nginx is our web server. It will listen for web requests (which are generated by
our users visiting our web application using their browsers) and hand these requests over to our Flask application.
As our application is in Python, we also need WSGI (Web Server Gateway Interface).
This is a common interface between web servers and Python applications, which allows nginx to talk to Flask and vice versa.
'''


@app.route('/')
def hello():
    return "Hello World!"

@app.route('/<name>')
def hello_name(name):
    return "Hello {}!".format(name)

if __name__ == '__main__':
    app.run(host='0.0.0.0')
